# PostgreSQL en RDS
# REEMPLAZA el valor de abajo con tu endpoint real de RDS
# Ejemplo: cafesoftdb.abc123xyz.mx-central-1.rds.amazonaws.com
spring.datasource.url=jdbc:postgresql://database-1.cxcoma0o05g2.mx-central-1.rds.amazonaws.com:5432/cafesoftbdpost
spring.datasource.username=postgres
spring.datasource.password=Patitofeo777
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto
server.port=8080

# Swagger (puedes desactivarlo en prod si quieres)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
